### ISSUE TITLE
Training with a different dataset

### ISSUE THREAD

**Issue by bionictoucan** [SeungjunNah/DeepDeblur_release#20]
Hi Seungjun,
I am currently trying to train the network with a different dataset than the GoPRO to help deblur the images I am using. I'm having a problem in getting the code to recognise my dataset though. I currently have my images saved in DeepDeblur_release/dataset/TrainingPairs/train/1/ then I have the images split into blur and sharp like the GOPRO dataset. When training the model I change the dataset option to be "TrainingPairs" and expected everything else to work fine due to the same layers of directories etc. being used as the GoPRO dataset.

However, in running this, I receive the error "/home/armstrong/DeepDeblur_release/code/donkey.lua:138: attempt to get length of global 'train_list' (a nil value)". This seems to imply that it cannot find the data I am trying to train with. I was wondering if there is something off about how I am structuring the path to my training data? I hope you can help.

Kind regards,
John Armstrong

**Comment by SeungjunNah** [comment]
Hi John,

The source code looks into different locations with optional arguments, 'dataset' and 'blur_type.'
By default, it assumes the GoPro dataset and 'gamma2.2' synthesized blur images.
Had you typed ```th main.lua -dataset TrainingPairs```, an example of blur directory should be:
```bash
DeepDeblur_release/dataset/TrainingPairs/train/1/blur_gamma
```
Then it wouldn't find any data on that location since your blur data is on
```bash
DeepDeblur_release/dataset/TrainingPairs/train/1/blur
```
You can run the source code by modifying input arguments as:
```bash
th main.lua -dataset TrainingPairs -blur_type linear
```
Please take a look at [opts.lua line 27](https://github.com/SeungjunNah/DeepDeblur_release/blob/master/code/opts.lua#L27) and [data.lua line 29-77](https://github.com/SeungjunNah/DeepDeblur_release/blob/master/code/data.lua#L29).

**Comment by bionictoucan** [comment]
Hi Seungjun,

Thank you very much! Problem solved.

Best wishes,
John
