### ISSUE TITLE
processing speed and image resolution

### ISSUE THREAD

**Issue by shockjiang** [SeungjunNah/DeepDeblur_release#24]
I tried to run the demo with GPU with my own image. However, it gave me some observations:
- image resolution cannot be as large as 3000x3000
- running speed is about 5sec per picture.

I run the program with Ubuntu 16.04 + TITAN-X. I wonder are the above two observations is as expected?

**Comment by SeungjunNah** [comment]
Theoretically, there should be no limits for the image resolution as the image can be cropped with overlapping regions. However, the current demo doesn't support the functionality.

Regarding the running speed, are you specifically referring to the provided HD resolution demo?
If so, it contains delay of 3 seconds while the actual processing time takes about 3 seconds in GTX Titan X (Mawell).
For 3000x3000 image, I'm not sure since I have never ran that resolution. Considering the resolution ratio, `3000^2/(1280x720)~=9.8`, It may take about 30 seconds.

**Comment by shockjiang** [comment]
Have you ever tried to test an image with resolution 3000x3000? I got "out of memory" even with TITAN-X.

**Comment by SeungjunNah** [comment]
No, I was just talking about theoretical speed, never tried.

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
