### ISSUE TITLE
What's the difference of linear and gamma2.2?

### ISSUE THREAD

**Issue by tornadomeet** [SeungjunNah/DeepDeblur_release#3]
hello, @SeungjunNah 

thanks for great work!  i just see we need set `-blur_type` during training, so what does it(camera response function) actually mean? does it mean we need add some noise on the input data which is blurred?  and different blur_type means different noise?

and what's the difference of linear and gamma2.2? Does it mean we need train the corresponding model for each? but in blind deblur area we don't know the camera response function in advance, so how to use it? 

i just read the paper about the process of gamma2.2 blur image generate, it first use do inverse gamma2.2 of the sharp image, and then do average using equation 2, then get the blurred image. what I am confused is that: do we need do gamma2.2 after do the average? （it seems that we should not do that from paper, but in the real world, i think we need fitting the CRF.）

another, which model(gamma2.2 or linear) is better evaluated on  Kohler Dataset dataset(both are trained on GOPRO dataset)？

thanks.

**Comment by SeungjunNah** [comment]
Hi @tornadomeet,

1. CRF (camera response function)
When taking a photo, roughly saying, the stimulus from camera sensor forms a RAW image. Then a nonlinear function is applied to the RAW values to generate pixel values in the range [0, 255]. The nonlinear function is called CRF, and it varies from camera to camera.
The average of CRFs is known to be a gamma function.
You may want to look at Tai et al.'s paper that describes blurry image generation process. https://careerfair.comp.nus.edu.sg/~brown/pdf/cvpr12_deblurCRF.pdf

In our blur generating process, we first estimate RAW values by applying inverse CRF to pixel values, and do averaging, and again transform the values from RAW space to pixel space.

2. The -blur_type option is used to select the CRF used to generate blurry images when averaging sharp frames. In this work, we decided to assume CRF is linear or gamma function (which is the average CRF) instead of actual unknown CRF. Thus, the models trained with linear CRF assumption works best when the real CRF is similar to linear or gamma function. In our experiments, the deblurred results from unmatched CRFs between image and trained model produces deblurred images with different thicknesses of objects.

3. For Kohler dataset, linear CRF assumption showed better performance in terms of PSNR. We will soon update our arXiv version paper and will provide a better description of CRF.

**Comment by tornadomeet** [comment]
Thansk @SeungjunNah  for great answer!  now i'm understand more. and i'll experiment the method from your paper on my project.
