### ISSUE TITLE
몇가지 궁금한게 있어 글을 씁니다.

### ISSUE THREAD

**Issue by Git-H2K** [SeungjunNah/DeepDeblur_release#6]
안녕하세요, 좋은 논문과 좋은 코드 공개해주셔서 감사합니다.
몇가지 궁금한 점이 있어 글을 습니다.

1. Table2,3 를 보면 K=1일때 가장 느리고, K=3일때 가장 빠른데요, K=3가 의미하는게 3-level이지 않나요? 하지만, K=1일때 가장 느리기 때문에, K=1일때가 3-level인 것 같은데 뭐가 맞는지 궁금합니다.

2. K=2일때 가장 성능이 좋았고, K=1일 때 가장 성능이 좋지 않았는데(느리고, PSNR이 낮음), 왜 기본 코드를 공개하실때나, 논문의 그림의 경우 3-level로 하신건가요?

3. Adversarial Loss의 경우 PSNR을 떨어트리는 효과가 있는데, 결과 비교가 PSNR로 비교가 되어있고, 다른 논문보다 PSNR이 높은데 이러한 것을 어떻게 해석해야 하나요? Adversarial Loss가 PSNR을 낮췄음에도 다른 논문보다 결과가 좋다고 해석을 해야될지, 아니면 Adversarial Loss에 곱해진 lambda값이 너무 작아서 효과가 미미한건지 궁금합니다.

4. 보통 3x3 convolutional layer가 성능이 더 좋고, 빨라서 많이 사용하는데,(3x3 conv layer 2개 = 5x5 conv layer), 5x5 convolutional layer를 쓰신 이유가 궁금합니다.

3주째 이 논문에 대해 분석을 하고 있는데, training하는데 시간이 오래걸리고, 막히는 부분이 많아 이렇게 글을 씁니다. 감사합니다.

**Comment by SeungjunNah** [comment]
Hi,
I'll answer in English so that other people could understand.
1. We fixed the number of total convolutional layers as 120. Thus, if you use more scales, the number of layers per scale decreases. Compared to K = 1 (120 layers for fine scale), K = 3 (40 layers for fine scale) uses much less computation and is faster.

2. I can't really say K=2 is always better than K=3 in terms of PSNR. When the blur kernel is large, K=3 tends to give better results. They give comparable results while K=3 is the fastest. So we chose K=3 as our release version.

3. If you don't use adversarial loss with our model, the PSNR becomes higher. So it is more appropriate to interpret that our model gives better PSNR even if the adversarial loss is used. Please refer to our supplementary material for loss comparison.

4. For deblurring, a large receptive field is preferred to handle large blur size. To maintain the same receptive field size with 3x3 filters, you need double amount of layers and GPU memory. It is more efficient to use 5x5 filters. If the number of layers is fixed, 5x5 filters give far better results compared to 3x3.

**Comment by Git-H2K** [comment]
좋은 답변 감사합니다! 많은 도움 됐습니다.
