### ISSUE TITLE
How to test REDS dataset?

### ISSUE THREAD

**Issue by Huangjianglu** [SeungjunNah/DeepDeblur_release#61]
Thanks for your great job!
I want to test my model on REDS dataset, but I can not download Test_Sharp.zip. How can I test my model on REDS dataset?

**Comment by SeungjunNah** [comment]
Hi @Huangjianglu,

The test GT is not publicly released as we are hosting NTIRE and AIM challenges based on the REDS dataset.
Currently evaluation is only available via challenge participation.

We are planning to run our own online server in a long term plan so that open-ended benchmark would be available to public.
However, it is not ready yet.
When we are ready, we will notice you.

**Comment by jinshuan001** [comment]
> Hi @Huangjianglu,
> 
> The test GT is not publicly released as we are hosting NTIRE and AIM challenges based on the REDS dataset.
> Currently evaluation is only available via challenge participation.
> 
> We are planning to run our own online server in a long term plan so that open-ended benchmark would be available to public.
> However, it is not ready yet.
> When we are ready, we will notice you.

**Comment by jinshuan001** [comment]
hi @SeungjunNah ,

I am engaged in the joint deblurring and super resolution job now and i wonder if i could send you my result on REDS test dataset to get a performance result

Best

Jinshuang

**Comment by SeungjunNah** [comment]
@jinshuan001 

Yes, I can give you the evaluated scores if you send me the images via email.
